name: Build and publish web demo
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  test-all:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.16'
      - run: go vet ./...
      - run: go test ./...
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # tinygo release 0.19.0
      - uses: docker://tinygo/tinygo-dev:sha-64d048c47c95bc0a70b4cff109afc1f9039705a4
        with:
          args: make build.handcheck.wasm.tinygo
      - uses: actions/upload-artifact@v2
        with:
          name: assets-wasm
          path: assets_tinygo/
          if-no-files-found: error
  publish-wasm:
    runs-on: ubuntu-latest
    needs: [test-all, build-wasm]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: nik0sc/nik0sc.github.io
          ref: master
      - run: rm -rf handcheck
      - uses: actions/download-artifact@v2
        with:
          name: assets-wasm
          path: handcheck
      - run: |
          git config --local user.email nik0sc+autodeploy@users.noreply.github.com
          git config --local user.name nik0sc+autodeploy
          git add handcheck
          git commit -m "Autodeploy for nik0sc/mj@${GITHUB_SHA::7}"
      - uses: ad-m/github-push-action@v0.6.0
        with:
          repository: nik0sc/nik0sc.github.io
          github_token: ${{secrets.PUBLISH_TOKEN}}
          branch: master