name: Go
on: [push]
jobs:
  test-all:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.16'
      - run: go vet ./...
      - run: go test ./...
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # tinygo release 0.19.0
      - uses: docker://tinygo/tinygo-dev:sha-64d048c47c95bc0a70b4cff109afc1f9039705a4
        with:
          args: make build.handcheck.wasm.tinygo
      - uses: actions/upload-artifact@v2
        with:
          name: Assets for wasm
          path: assets_tinygo/
          if-no-files-found: error
